name: ThumbsSlides
author: arieh
category: Interface
tags: [menus, behavioral, utilities]
#demo: http://tests.arieh.co.il/acord/demo.html
#docs: http://github.com/arieh/MooTreeAcordion/blob/master/Docs/MooTreeAcordion.md
current: 0.5